- name: Get vault credentials
  hosts: localhost
  connection: local
  tasks:
    - name: Print Password
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'test/my_credentials:password token={{ vault_token }} url=https://<IP>:8200 validate_certs=False') }}"